properties:
  name: Bottles runtime
  version: CHANGE_ME
  description: This is a set of librarires to ensure runners compatibility in Bottles
  author: mirkobrombin
  license: MIT
  url: https://github.com/bottlesdevs/runtime
packager: APT
system:
  name: CHANGE_ME
  min_version: CHANGE_ME
  max_version: CHANGE_ME
ingredients:
  - files:
      - libaio.so.1
    package: libaio1 libaio1:i386
  - files:
      - liballeg.so.4.4
    package: liballegro4.4 liballegro4.4:i386
  - files:
      - libatk-1.0.so.0
    package: libatk1.0-0 libatk1.0-0:i386
  - files:
      - libaudio.so.2
    package: libaudio2 libaudio2:i386
  - files:
      - libavcodec.so.59
    package: libavcodec59 libavcodec59:i386
  - files:
      - libavformat.so.59
    package: libavformat59 libavformat59:i386
  - files:
      - libavutil.so.57
    package: libavutil57 libavutil57:i386
  - files:
      - libswscale.so.6
    package: libswscale6 libswscale6:i386
  - files:
      - libenet.so.7
    package: libenet7 libenet7:i386
  - files:
      - libcairo.so.2
    package: libcairo2 libcairo2:i386
  - files:
      - libcdio.so.19
    package: libcdio19 libcdio19:i386
  - files:
      - libdatrie.so.1
    package: libdatrie1 libdatrie1:i386
  - files:
      - libfaad.so.2
    package: libfaad2 libfaad2:i386
  - files:
      - libfluidsynth.so.3
    package: libfluidsynth3 libfluidsynth3:i386
  - files:
      - libfribidi.so.0
    package: libfribidi0 libfribidi0:i386
  - files:
      - libfuse.so.2
    package: libfuse2 libfuse2:i386
  - files:
      - libfontconfig.so.1
    package: libfontconfig1 libfontconfig1:i386
  - files:
      - libfreetype.so.6
    package: libfreetype6 libfreetype6:i386
  - files:
      - libgcrypt.so.20
    package: libgcrypt20 libgcrypt20:i386
  - files:
      - libgpg-error.so.0
    package: libgpg-error0 libgpg-error0:i386
  - files:
      - libgdk-x11-2.0.so.0
    package: libgtk2.0-0 libgtk2.0-0:i386
  - files:
      - libgdk_pixbuf-2.0.so.0
    package: libgdk-pixbuf2.0-0 libgdk-pixbuf2.0-0:i386
  - files:
      - libgif.so.7
    package: libgif7 libgif7:i386
  - files:
      - libGLEW.so.2.2
    package: libglew2.2 libglew2.2:i386
  - files:
      - libgloox.so.18
    package: libgloox18 libgloox18:i386
  - files:
      - libgnutls.so.30
      - libnettle.so.6
      - libhogweed.so.4
      - libgmp.so.10
      - libtasn1.so.6
      - libidn2.so.0
    package: libgnutls30 libgnutls30:i386
  - files:
      - libgomp.so.1
    package: libgomp1 libgomp1:i386
  - files:
      - libgraphite2.so.3
    package: libgraphite2-3 libgraphite2-3:i386
  - files:
      - libharfbuzz.so.0
    package: libharfbuzz0b libharfbuzz0b:i386
  - files:
      - libicui18n.so.72
      - libicuuc.so.72
      - libicudata.so.72
    package: libicu72 libicu72:i386
  - files:
      - libIrrlicht.so.1.8
    package: libirrlicht1.8 libirrlicht1.8:i386
  - files:
      - libjansson.so.4
    package: libjansson4 libjansson4:i386
  - files:
      - libjbig.so.0
    package: libjbig0 libjbig0:i386
  - files:
      - libjson-c.so.5
    package: libjson-c5 libjson-c5:i386
  - files:
      - libldap-2.5.so.0
      - liblber-2.5.so.0
    package: libldap-2.5-0 libldap-2.5-0:i386
  - files:
      - libsasl2.so.2
    package: libsasl2-2 libsasl2-2:i386
  - files:
      - libgssapi.so.3
    package: libgssapi3-heimdal libgssapi3-heimdal:i386
  - files:
      - libheimntlm.so.0
    package: libheimntlm0-heimdal libheimntlm0-heimdal:i386
  - files:
      - libkrb5.so.26
    package: libkrb5-26-heimdal libkrb5-26-heimdal:i386
  - files:
      - libasn1.so.8
    package: libasn1-8-heimdal libasn1-8-heimdal:i386
  - files:
      - libcom_err.so.2
    package: libcom-err2 libcom-err2:i386
  - files:
      - libhcrypto.so.5
    package: libhcrypto5-heimdal libhcrypto5-heimdal:i386
  - files:
      - libroken.so.19
    package: libroken19-heimdal libroken19-heimdal:i386
  - files:
      - libwind.so.0
    package: libwind0-heimdal libwind0-heimdal:i386
  - files:
      - libheimbase.so.1
    package: libheimbase1-heimdal libheimbase1-heimdal:i386
  - files:
      - libhx509.so.5
    package: libhx509-5-heimdal libhx509-5-heimdal:i386
  - files:
      - libleveldb.so.1d
    package: libleveldb1d libleveldb1d:i386
  - files:
      - liblua5.1.so.0
    package: liblua5.1-0 liblua5.1-0:i386
  - files:
      - liblua5.2.so.0
    package: liblua5.2-0 liblua5.2-0:i386
  - files:
      - libluajit-5.1.so.2
    package: libluajit-5.1-2 libluajit-5.1-2:i386
  - files:
      - libmad.so.0
    package: libmad0 libmad0:i386
  - files:
      - libmikmod.so.3
    package: libmikmod3 libmikmod3:i386
  - files:
      - libminiupnpc.so.17
    package: libminiupnpc17 libminiupnpc17:i386
  - files:
      - libmodplug.so.1
    package: libmodplug1 libmodplug1:i386
  - files:
      - libmpeg2.so.0
      - libmpeg2convert.so.0
    package: libmpeg2-4 libmpeg2-4:i386
  - files:
      - libmpg123.so.0
    package: libmpg123-0 libmpg123-0:i386
  - files:
      - libncurses.so.5
    package: libncurses5 libncurses5:i386
  - files:
      - libncursesw.so.5
    package: libncursesw5 libncursesw5:i386
  - files:
      - libjpeg.so.62
    package: libjpeg62-turbo libjpeg62-turbo:i386
  - files:
      - libhistory.so.8
      - libreadline.so.8
    package: libreadline8 libreadline8:i386
  - files:
      - libpango-1.0.so.0
    package: libpango-1.0-0 libpango-1.0-0:i386
  - files:
      - libpangocairo-1.0.so.0
    package: libpangocairo-1.0-0 libpangocairo-1.0-0:i386
  - files:
      - libpangoft2-1.0.so.0
    package: libpangoft2-1.0-0 libpangoft2-1.0-0:i386
  - files:
      - libphysfs.so.1
    package: libphysfs1 libphysfs1:i386
  - files:
      - libportaudio.so.2
    package: libportaudio2 libportaudio2:i386
  - files:
      - libpulse-simple.so.0
      - libpulse.so.0
      - libpulsecommon-11.1.so
    package: libpulse0 libpulse0:i386
  - files:
      - libSDL2_image-2.0.so.0
    package: libsdl2-image-2.0-0 libsdl2-image-2.0-0:i386
  - files:
      - libSDL2_mixer-2.0.so.0
    package: libsdl2-mixer-2.0-0 libsdl2-mixer-2.0-0:i386
  - files:
      - libSDL2_ttf-2.0.so.0
    package: libsdl2-ttf-2.0-0 libsdl2-ttf-2.0-0:i386
  - files:
      - libSDL_net-1.2.so.0
    package: libsdl-net1.2 libsdl-net1.2:i386
  - files:
      - libSDL_sound-1.0.so.1
    package: libsdl-sound1.2 libsdl-sound1.2:i386
  - files:
      - libSDL_ttf-2.0.so.0
    package: libsdl-ttf2.0-0 libsdl-ttf2.0-0:i386
  - files:
      - libsnappy.so.1
    package: libsnappy1v5 libsnappy1v5:i386
  - files:
      - libsndio.so.7
    package: libsndio7.0 libsndio7.0:i386
  - files:
      - libSoundTouch.so.1
    package: libsoundtouch1 libsoundtouch1:i386
  - files:
      - libsoxr.so.0
    package: libsoxr0 libsoxr0:i386
  - files:
      - libstdc++.so.5
    package: libstdc++5 libstdc++5:i386
  - files:
      - libthai.so.0
    package: libthai0 libthai0:i386
  - files:
      - libtiff.so.6
    package: libtiff6 libtiff6:i386
  - files:
      - libtinfo.so.5
    package: libtinfo5 libtinfo5:i386
  - files:
      - libupnp.so.13
    package: libupnp13 libupnp13:i386
  - files:
      - libv4lconvert.so.0
    package: libv4lconvert0 libv4lconvert0:i386
  - files:
      - libwebp.so.7
    package: libwebp7 libwebp7:i386
  - files:
      - libwx_baseu-3.2.so.0
    package: libwxbase3.2-1 libwxbase3.2-1:i386
  - files:
      - libwx_gtk3u_core-3.2.so.0
      - libwx_gtk3u_adv-3.2.so.0
    package: libwxgtk3.2-1 libwxgtk3.2-1:i386
  - files:
      - libx264.so.164
    package: libx264-164 libx264-164:i386
  - files:
      - libXinerama.so.1
    package: libxinerama1 libxinerama1:i386
  - files:
      - libxshmfence.so.1
    package: libxshmfence1 libxshmfence1:i386
  - files:
      - libxml2.so.2
    package: libxml2 libxml2:i386
  - files:
      - libxslt.so.1
      - libexslt.so.0
    package: libxslt1.1 libxslt1.1:i386
  - files:
      - libzzip-0.so.13
    package: libzzip-0-13 libzzip-0-13:i386
  - files:
      - libz.so.1
    package: zlib1g zlib1g:i386
  - files:
      - libcurl.so.4
    package: libcurl4 libcurl4:i386
  - files:
      - libnghttp2.so.14
    package: libnghttp2-14 libnghttp2-14:i386
  - files:
      - libpcre.so.3
    package: libpcre3 libpcre3:i386
  - files:
      - libpsl.so.5
    package: libpsl5 libpsl5:i386
  - files:
      - libcrypto.so.3
      - libssl.so.3
    package: libssl3 libssl3:i386
  - files:
      - libunistring.so.2
    package: libunistring2 libunistring2:i386
  - files:
      - libuuid.so.1
    package: libuuid1 libuuid1:i386
  - files:
      - librtmp.so.1
    package: librtmp1 librtmp1:i386
  - files:
      - libXtst.so.6
    package: libxtst6 libxtst6:i386
  - files:
      - libvpx.so.7
    package: libvpx7 libvpx7:i386
  - files:
      - libcrypt.so.1
    package: libcrypt1 libcrypt1:i386
  - files:
      - libpcre.so.3
    package: libpcre3 libpcre3:i386
