properties:
  name: Bottles runtime
  version: 0.6.2
  description: This is a set of librarires from Ubuntu 20.04 to ensure runners compatibility in Bottles
  author: mirkobrombin
  license: MIT
  url: https://github.com/bottlesdevs/runtime

packager: Aptitude

system:
  name: Ubuntu
  min_version: 20.04
  max_version: 20.04
  
ingredients:
  - files:
    - libSDL2_mixer-2.0.so.0
    package: libsdl2-mixer-2.0-0 libsdl2-mixer-2.0-0:i386

  - files:
    - libsoxr.so.0
    package: libsoxr0 libsoxr0:i386

  - files:
    - libdatrie.so.1
    package: libdatrie1 libdatrie1:i386

  - files:
    - libwx_baseu-3.0.so.0
    package: libwxbase3.0-0v5 libwxbase3.0-0v5:i386

  - files:
    - liblua5.2.so.0
    package: liblua5.2-0 liblua5.2-0:i386

  - files:
    - libjbig.so.0
    package: libjbig0 libjbig0:i386

  - files:
    - libjpeg.so.8
    package: libjpeg-turbo8 libjpeg-turbo8:i386

  - files:
    - libfribidi.so.0
    package: libfribidi0 libfribidi0:i386

  - files:
    - libxslt.so.1
    package: libxslt1.1 libxslt1.1:i386

  - files:
    - libtiff.so.5
    package: libtiff5 libtiff5:i386

  - files:
    - libmad.so.0
    package: libmad0 libmad0:i386

  - files:
    - libtinfo.so.5
    package: libtinfo5 libtinfo5:i386

  - files:
    - libmpg123.so.0
    package: libmpg123-0 libmpg123-0:i386

  - files:
    - libfaad.so.2
    package: libfaad2 libfaad2:i386

  - files:
    - libgomp.so.1
    package: libgomp1-i386-cross libgomp1-i386-cross:i386

  - files:
    - libaudio.so.2
    package: libaudio2 libaudio2:i386

  - files:
    - libmikmod.so.3
    package: libmikmod3 libmikmod3:i386

  - files:
    - libexslt.so.0
    package: libxslt1.1 libxslt1.1:i386

  - files:
    - libSDL2_image-2.0.so.0
    package: libsdl2-image-2.0-0 libsdl2-image-2.0-0:i386

  - files:
    - libxshmfence.so.1
    package: libxshmfence1 libxshmfence1:i386

  - files:
    - libthai.so.0
    package: libthai0 libthai0:i386

  - files:
    - libSDL_net-1.2.so.0
    package: libsdl-net1.2 libsdl-net1.2:i386

  - files:
    - libgcrypt.so.20
    package: libgcrypt20 libgcrypt20:i386

  - files:
    - libSoundTouch.so.1
    package: libsoundtouch1 libsoundtouch1:i386

  - files:
    - libportaudio.so.2
    package: libportaudio2 libportaudio2:i386

  - files:
    - liblua5.1.so.0
    package: liblua5.1-0 liblua5.1-0:i386

  - files:
    - libgif.so.7
    package: libgif7 libgif7:i386

  - files:
    - libatk-1.0.so.0
    package: libatk1.0-0 libatk1.0-0:i386

  - files:
    - libSDL_sound-1.0.so.1
    package: libsdl-sound1.2 libsdl-sound1.2:i386

  - files:
    - libgraphite2.so.3
    package: libgraphite2-3 libgraphite2-3:i386

  - files:
    - libluajit-5.1.so.2
    package: libluajit-5.1-2 libluajit-5.1-2:i386

  - files:
    - libwebp.so.6
    package: libwebp6 libwebp6:i386

  - files:
    - libmodplug.so.1
    package: libmodplug1 libmodplug1:i386

  - files:
    - libmpeg2.so.0
    package: libmpeg2-4 libmpeg2-4:i386

  - files:
    - libSDL_ttf-2.0.so.0
    package: libsdl-ttf2.0-0 libsdl-ttf2.0-0:i386

  - files:
    - libjansson.so.4
    package: libjansson4 libjansson4:i386

  - files:
    - libz.so.1
    package: zlib1g zlib1g:i386

  - files:
    - libncurses.so.5
    package: libncurses5 libncurses5:i386

  - files:
    - libXinerama.so.1
    package: libxinerama1 libxinerama1:i386

  - files:
    - libzzip-0.so.13
    package: libzzip-0-13 libzzip-0-13:i386

  - files:
    - libfuse.so.2
    package: libfuse2 libfuse2:i386

  - files:
    - libgpg-error.so.0
    package: libgpg-error0 libgpg-error0:i386

  - files:
    - libv4lconvert.so.0
    package: libv4lconvert0 libv4lconvert0:i386

  - files:
    - libncursesw.so.5
    package: libncursesw5 libncursesw5:i386

  - files:
    - libmpeg2convert.so.0
    package: libmpeg2-4 libmpeg2-4:i386

  - files:
    - libfontconfig.so.1
    package: libfontconfig1 libfontconfig1:i386

  - files:
    - libxml2.so.2
    package: libxml2 libxml2:i386

  - files:
    - libharfbuzz.so.0
    package: libharfbuzz0b libharfbuzz0b:i386

  - files:
    - libaio.so.1
    package: libaio1 libaio1:i386
